import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cn } from "~/lib/utils";
import Navbar from "~/components/ui/Navbar";
import { ClerkProvider } from '@clerk/nextjs'


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased ",
          inter.variable
        )}
      >
        <Navbar />
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
